In [4]:
from bs4 import BeautifulSoup as bs 
import requests
import re
import json

In [6]:
base = 'https://www.aladin.co.kr/shop/common/wbest.aspx?BestType=Bestseller&BranchType=1&CID=0&page='
url = 'https://www.aladin.co.kr/shop/common/wbest.aspx?BranchType=1'
books=[]
for i in range(3):
    url = base+str(i+1)
    res = requests.get(url)
    soup = bs(res.text, 'html.parser')

    book_list =soup.findAll('div', {'class':'ss_book_list'})
    for index, book in enumerate(book_list):
        print(index)
        if index % 2 == 0:
            print(f'index: {index*(i+1)}')
            book_ul = book.find('ul')
            title = book_ul.find('a',{'class':'bo3'}).text
            # print(f'title: {title}')
            book_price = ""
            book_author = ""
            book_li_list = book_ul.findAll('li')
            # print(book_li_list)
            price = book_li_list[3].find('span').text.replace(',','')
            print(f'price: {price}')
            author = book_li_list[2].find('a')
            if author != None:
                author = author.text
            else:
                author = book_li_list[1].find('a').text
            print(f'author: {author}')
            books.append((title, int(price), author))
            # print(book_ul)
            # break

0
index: 0
price: 15000
author: 한강
1
2
index: 2
price: 16800
author: 존 윌리엄스
3
4
index: 4
price: 18800
author: 김주환
5
6
index: 6
price: 17000
author: 백수린
7
8
index: 8
price: 18000
author: 최재천
9
10
index: 10
price: 17800
author: 코이케 류노스케
11
12
index: 12
price: 21000
author: 이선 몰릭
13
14
index: 14
price: 13000
author: 양귀자
15
16
index: 16
price: 16500
author: 최태성
17
18
index: 18
price: 19800
author: ETS
19
20
index: 20
price: 22000
author: 황현필
21
22
index: 22
price: 19800
author: ETS
23
24
index: 24
price: 12900
author: David Cho
25
26
index: 26
price: 17800
author: 이경규
27
28
index: 28
price: 16000
author: 최태성
29
30
index: 30
price: 15000
author: 한강
31
32
index: 32
price: 17800
author: 태수
33
34
index: 34
price: 16800
author: 한강
35
36
index: 36
price: 18000
author: 앨 앨버레즈
37
38
index: 38
price: 21000
author: 안-엘렌 클레르
39
40
index: 40
price: 21800
author: 히가시노 게이고
41
42
index: 42
price: 14000
author: 정대건
43
44
index: 44
price: 6000
author: 무치마로
45
46
index: 46
price: 40000
author: Dave
47
48
index: 48
price: 49000
author: 그레고리 맨큐
49
50
index: 50
price: 27000
author: 오건영
51
52
index: 52
price: 26000
author: 오태민
53
54
index: 54
price: 13000
author: 지누시
55
56
index: 56
price: 10000
author: 무치마로
57
58
index: 58
price:  116820
author: 한동훈
59
60
index: 60
price: 18000
author: 존 윌리엄스
61
62
index: 62
price: 16700
author: 매튜 맥커너히
63
64
index: 64
price: 15000
author: 성승현
65
66
index: 66
price: 20000
author: 홍한별
67
68
index: 68
price: 17500
author: 예소연
69
70
index: 70
price: 13800
author: 클레어 키건
71
72
index: 72
price: 16900
author: 브라이언 트레이시
73
74
index: 74
price: 25000
author: 박이도
75
76
index: 76
price: 15000
author: 설상록
77
78
index: 78
price: 17000
author: 에드워드 애슈턴
79
80
index: 80
price: 22000
author: 이어령
81
82
index: 82
price: 23800
author: 유선경
83
84
index: 84
price: 32000
author: 천인국
85
86
index: 86
price: 28000
author: 빌 게이츠
87
88
index: 88
price: 19000
author: 크리스타 K. 토마슨
89
90
index: 90
price: 14000
author: 박준철
91
92
index: 92
price: 38000
author: 청연
93
94
index: 94
price: 6000
author: 아오야마 고쇼
95
96
index: 96
price: 24000
author: 모쿠모쿠렌
97
98
index: 98
price: 40000
author: Dave
99
0
index: 0
price: 29000
author: 이유진
1
2
index: 4
price: 6000
author: 호리코시 코헤이
3
4
index: 8
price: 27800
author: 유발 하라리
5
6
index: 12
price: 27000
author: 에드워드 애슈턴
7
8
index: 16
price: 17800
author: 박진여
9
10
index: 20
price: 18000
author: ETS
11
12
index: 24
price: 5500
author: 대한민국
13
14
index: 28
price: 22000
author: 스티븐 레비츠키
15
16
index: 32
price: 14500
author: 한강
17
18
index: 36
price: 19000
author: 채사장
19
20
index: 40
price: 19900
author: 바버라 오클리
21
22
index: 44
price: 33000
author: 나홍석
23
24
index: 48
price: 18000
author: 정규영
25
26
index: 52
price: 19500
author: 최태성
27
28
index: 56
price:  3660
author: 윤혜정
29
30
index: 60
price: 12000
author: 고선경
31
32
index: 64
price: 17000
author: 윤성희
33
34
index: 68
price: 18000
author: 우케쓰
35
36
index: 72
price: 16800
author: 일본어 공부기술연구소
37
38
index: 76
price: 6500
author: 스즈키 유우토
39
40
index: 80
price: 35000
author: Erwin Kreyszig
41
42
index: 84
price: 3300
author: 헤르만 헤세
43
44
index: 88
price: 13000
author: 김소형
45
46
index: 92
price: 26000
author: 후지이 아사리
47
48
index: 96
price: 20000
author: 김종원
49
50
index: 100
price: 18000
author: 찰리 맥커시
51
52
index: 104
price: 13000
author: ETS
53
54
index: 108
price: 22000
author: 알베르 카뮈
55
56
index: 112
price: 22800
author: 임용한
57
58
index: 116
price: 56000
author: Steven S. Zumdahl
59
60
index: 120
price: 18000
author: 이선재
61
62
index: 124
price: 15000
author: 문동균
63
64
index: 128
price: 8000
author: 헤르만 헤세
65
66
index: 132
price: 20000
author: 김종원
67
68
index: 136
price: 15000
author: 곽미영
69
70
index: 140
price: 32000
author: 권석만
71
72
index: 144
price: 18800
author: David Cho
73
74
index: 148
price: 22000
author: 벤저민 하디
75
76
index: 152
price: 13000
author: 동국대학교 건학위원회
77
78
index: 156
price: 28000
author: 나유리
79
80
index: 160
price: 20000
author: 리처드 도킨스
81
82
index: 164
price: 52000
author: Raymond A. Serway
83
84
index: 168
price: 14000
author: 설민석
85
86
index: 172
price: 14400
author: 심우철
87
88
index: 176
price:  10060
author: 이종학
89
90
index: 180
price: 19000
author: 윤규철
91
92
index: 184
price: 55000
author: Theodore L. Brown
93
94
index: 188
price: 6500
author: 모쿠모쿠렌
95
96
index: 192
price: 18000
author: 김금희
97
98
index: 196
price: 12000
author: 문동균
99
0
index: 0
price: 18000
author: 도야마 시게히코
1
2
index: 6
price: 19000
author: 윤규철
3
4
index: 12
price: 21000
author: 오빠두(전진권)
5
6
index: 18
price: 19800
author: 존 R. 마일스
7
8
index: 24
price: 17800
author: 돌리 앨더튼
9
10
index: 30
price: 19000
author: 김종원
11
12
index: 36
price: 5500
author: 데일 카네기
13
14
index: 42
price: 6000
author: 타카마츠 미사키
15
16
index: 48
price: 22000
author: 필립 바구스
17
18
index: 54
price: 49000
author: James Stewart
19
20
index: 60
price: 12000
author: 한강
21
22
index: 66
price: 374000
author: 이우혁
23
24
index: 72
price: 34000
author: 프란치스코 교황
25
26
index: 78
price: 11000
author: 이동기
27
28
index: 84
price: 18900
author: 김재우
29
30
index: 90
price:  8150
author: 제인 심
31
32
index: 96
price: 18000
author: 정은숙
33
34
index: 102
price: 32500
author: 정수봉
35
36
index: 108
price: 17500
author: 정보라
37
38
index: 114
price: 16800
author: 스티븐 레비츠키
39
40
index: 120
price: 19000
author: 크리스 휘타커
41
42
index: 126
price: 43000
author: 이준구
43
44
index: 132
price: 18000
author: 이선재
45
46
index: 138
price: 16800
author: 김기태
47
48
index: 144
price: 19800
author: 모건 하우절
49
50
index: 150
price: 17000
author: ETS
51
52
index: 156
price: 14000
author: 단꿈아이
53
54
index: 162
price: 22000
author: 이창섭(BTOB)
55
56
index: 168
price: 20000
author: 말콤 글래드웰
57
58
index: 174
price: 25000
author: 살만 칸
59
60
index: 180
price: 33000
author: 장영광
61
62
index: 186
price: 22000
author: 권석만
63
64
index: 192
price: 13000
author: 한강
65
66
index: 198
price: 22000
author: 스콧 갤러웨이
67
68
index: 204
price: 40000
author: 윤영빈
69
70
index: 210
price: 19800
author: 해커스어학연구소
71
72
index: 216
price: 19000
author: 최재천
73
74
index: 222
price: 20000
author: 김난도
75
76
index: 228
price: 18800
author: David Cho
77
78
index: 234
price: 18000
author: 이은희
79
80
index: 240
price: 16800
author: 김지훤
81
82
index: 246
price: 16900
author: David Cho
83
84
index: 252
price: 6000
author: 메구로 아무
85
86
index: 258
price: 25000
author: 데이비드 이글먼
87
88
index: 264
price: 24000
author: 리처드 피셔
89
90
index: 270
price: 27000
author: 권중돈
91
92
index: 276
price: 22000
author: 주단
93
94
index: 282
price: 13500
author: 김은영
95
96
index: 288
price: 22000
author: 조수용
97
98
index: 294
price: 60000
author: Lisa A. Urry
99

In [7]:
import pandas as pd 
df=pd.DataFrame(books,columns=['title','price','author'])
df.to_csv('books.csv',index=False)
#len(books)
df

                   title  price        author
0                 소년이 온다  15000            한강
1                    스토너  16800        존 윌리엄스
2                그릿 Grit  18800           김주환
3               봄밤의 모든 것  17000           백수린
4                     양심  18000           최재천
..                   ...    ...           ...
145      사회복지학개론 (권중돈 외)  27000           권중돈
146  수학 진짜 잘하는 법을 알려줄게요.  22000            주단
147         어느 날 문이 사라졌다  13500           김은영
148                일의 감각  22000           조수용
149              캠벨 생명과학  60000  Lisa A. Urry

[150 rows x 3 columns]

In [8]:
import pymysql
conn=pymysql.connect(
    host='localhost',
    user='yubeen',
    password='1234',
    db='pydb',
    charset='utf8')
print(conn)
cursor=conn.cursor()
sql="insert into tblbook(title,price,author) values(%s,%s,%s)"
cursor.executemany(sql,books)
conn.commit()
conn.close()

<pymysql.connections.Connection object at 0x000002E991ECFF50>